[programs.localnet]
tic_tac_toe = "82iBFv96TfdP11584tHdMzw8kCqCjuak5xMkLa5yWwTd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_py = "anchorpy client-gen target/idl/tic_tac_toe.json py_client && python test.py" 
